import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "sonner";
import Footer from "./_components/Footer";

// Define the Montserrat font with both woff and woff2 formats for better compatibility
const montserrat = localFont({
  src: [{ path: "./fonts/Montserrat-Regular.woff", weight: "400" }],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <style>{montserrat.styles}</style>
      </head>
      <body className={`${montserrat.variable} antialiased`}>
        <NextAuthSessionProvider>
          <div className="mx-6 md:mx-16 lg:mx-0">
            <Header />
            <Toaster />
            {children}
            <Footer />
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
