import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";

const montserrat = localFont({
  src: "./fonts/Montserrat-Regular.woff",
  variable: "--font-montserrat",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <div className="mx-6 md:mx-16">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
