export const SERVICE_LOAD_REQUEST = "SERVICE_LOAD_REQUEST";
export const SERVICE_LOAD_SUCCESS = "SERVICE_LOAD_SUCCESS";
export const SERVICE_LOAD_FAIL = "SERVICE_LOAD_FAIL";
export const SERVICE_LOAD_RESET = "SERVICE_LOAD_RESET";
