export const SERVICE_CATEGORY_REQUEST = "SERVICE_CATEGORY_REQUEST";
export const SERVICE_CATEGORY_SUCCESS = "SERVICE_CATEGORY_SUCCESS";
export const SERVICE_CATEGORY_FAIL = "SERVICE_CATEGORY_FAIL";
export const SERVICE_CATEGORY_RESET = "SERVICE_CATEGORY_RESET";
