export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_RESET = "USER_LOAD_RESET";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";

export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const SERVICE_POST_REQUEST = 'SERVICE_POST_REQUEST';
export const SERVICE_POST_SUCCESS = 'SERVICE_POST_SUCCESS';
export const SERVICE_POST_FAIL = 'SERVICE_POST_FAIL';
